version: '3.4'

x-common-variables: &common-variables
  HSELING_RPC_ENDPOINT: http://hse-api-web:80/rpc/
  HSELING_API_ENDPOINT: http://hse-api-web:80/api/
  RESTRICTED_MODE: 0

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-midrusnlp/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: ./hseling-api-midrusnlp/hseling_api_midrusnlp
        target: /app/hseling_api_midrusnlp
      - type: bind
        source: ./hseling-data-midrusnlp/api
        target: /data
    environment: *common-variables






  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-midrusnlp/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-web-midrusnlp/hseling_web_midrusnlp
        target: /app/hseling_web_midrusnlp
      - type: bind
        source: ./hseling-web-midrusnlp/hseling_web_midrusnlp/static
        target: /app/static
      - type: bind
        source: ./hseling-data-midrusnlp/web
        target: /data
